#
# Core APRS Client
# APRS pre-processor stub
# Author: Joerg Schultze-Lutter, 2025
#
# This is a stub for the module which generates the outgoing APRS message
# (based on what the user wants you to do)
#
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

# These keywords are STUBS which also assume that the data parameters (originating
# from the input_processor) are forwarded as a 'dict' object. You need to modify
# this code according to your very own use case.
#

from CoreAprsClient import CoreAprsClient


def pre_processing(
    instance: CoreAprsClient, aprs_message: str, from_callsign: str, **kwargs
):
    """
    This is a stub for your custom APRS pre-processor.

    Parameters
    ==========
    instance: CoreAprsClient
        Instance of the core-aprs-client object.
    aprs_message: str
        The APRS message that the user has provided us with (1..67
        bytes in length). Parse the content and figure out what
        the user wants you to do.
    from_callsign: str
        Ham radio callsign that sent the message to us.
        Might be required by the input processor e.g. in case you
        have to determine the from_callsign's latitude/longitude.
    **kwargs: dict
        Optional keyword arguments

    Returns
    =======
    success: bool
        True if everything is fine, False otherwise. Used in combination with
        pre_processor_response_message
    pre_processor_response_message: str | None
        if 'success' is 'True' AND "pre_processor_response_message" is 'str' AND
        len(pre_processor_response_message) > 0, then the framework will send this
        message to the user prior to starting the input parser parse process.
    """

    return True, "This message text is generated by the pre_processor.py program file"


if __name__ == "__main__":
    pass
